---
abstract: 'load multiple config files.'
author:
  - 'Tomohiro Teranishi <tomohiro.teranishi@gmail.com>'
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-Multi
no_index:
  directory:
    - inc
    - t
recommends:
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Test::Spelling: 0
requires:
  Class::Accessor: 0
  Config::Any: 0
  Data::Visitor::Encode: 0
  DirHandle: 0
  Test::Base: 0
  YAML::Syck: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
